import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";

import Navbar from "../components/Components/Navbar";
import Hero from "@/components/Components/Hero";
import Menu from "@/components/Components/Menu";
import VStack from "@/components/Layout/VStack";
import HStack from "@/components/Layout/HStack";
import Button from "@/components/Bricks/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar></Navbar>
      <Hero></Hero>
      <VStack
        style=' items-center relative w-full   overflow-hidden  rtl:ml-0  mt-24  bg-gradient-to-t from-primary to-transparent pt-28 md:pt-64 justify-center h-screen'
        id='scopri'
      >
        <HStack style=' items-center  '>
          <div className='  lg:w-3/4  h-fit  w-full ml-16 max-lg:ml-6 z-20 '>
            <p className='lg:text-9xl max-lg:text-6xl font-miofont  font-bold  text-white text-center leading-10'>
              Spirito tradizionale ma attento al futuro
            </p>
          </div>
          <div className=' absolute top-15  -right-60  '>
            <Image
              alt=''
              className='myimg  '
              src='/motto.png'
              width={1000}
              height={1000}
            ></Image>
          </div>
        </HStack>

        <Link href='/about'>
          <Button style=' relative py-8 px-10 bg-secondary text-center font-miofont font-bold text-2xl my-7  '>
            Leggi la nostra storia
          </Button>
        </Link>
      </VStack>
    </>
  );
}
