export const vini = [
  {
    id: "loc-op",
    località: "Oltrepò",
    categorie: [
      {
        id: "bol",
        title: "Bollicine",
        items: [
          {
            id: 0,
            name: "Travaglino",
            description:
              "Grand Cuvee Blanc de Noir Oltrepò P. Docg Extra Brut 2018",
            vol: "Pinot Nero 100% (vol 13%)",
            price: 47,
          },
          {
            id: 1,
            name: "Az. Agr. Torrazzetta",
            description: "“Albore” Met. Cl. Vsq Extra Brut s.a.",
            vol: "Pinot nero 100% (vol. 13,5%)",
            price: 38,
          },
          {
            id: 2,
            name: "Marchesi di Montalto",
            description: "“Organza” Vsq Brut s.a.",
            vol: "Pinot Nero 70%, Riesling 30% (vol. 12%)",
            price: 34,
          },
          {
            id: 3,
            name: "Calatroni",
            description: "“Inganno 572” Vsq Brut s.a",
            vol: "Riesling 100% (vol. 12,5%)",
            price: 32,
          },
        ],
      },
      {
        id: "bol-rosè",
        title: "Bollicine Rosè",
        items: [
          {
            id: 0,
            name: "Calatroni",
            description: "“Norema” Met. Cl. Rosè P. Docg Extra Brut 2019",
            vol: "Pinot nero 100% (vol. 12,5%)",
            price: 40,
          },
          {
            id: 1,
            name: "Marchesi di Montalto",
            description: "“Costa del Vento” Met. Cl. Cruasè P. Docg Brut 2016",
            vol: "Pinot nero 100% (vol. 12,5%)",
            price: 37,
          },
          {
            id: 2,
            name: "Az. Agr. Torrazzetta",
            description: "“Aurora” Met. Cl. Rosè Vsq Non Dosato s.a.",
            vol: "Pinot nero 100% (vol. 13,5%)",
            price: 34,
          },
          {
            id: 3,
            name: "Piccolo Bacco dei Quaroni",
            description: "“La Posa” Met. Ancestrale Rosè Vsq Pas Dosè 2021",
            vol: "Barbera 100% (vol. 13,5%)",
            price: 26,
          },
        ],
      },
      {
        id: "bianchi-fermi",
        title: "Vini bianchi fermi",
        items: [
          {
            id: 0,
            name: "Marchesi di Montalto",
            description: "“VT” Riesling Sup. Oltrepo P. Doc 2021",
            vol: "Riesling Renano 100% (vol. 12%)",
            price: 35,
          },
          {
            id: 1,
            name: "Mon Carul",
            description: "“Campo Dottore” Riesling Riserva Oltrepo P. Doc 2019",
            vol: "Riesling Renano 100% (vol. 13%)",
            price: 33,
          },
          {
            id: 2,
            name: "Az. Agr Torrazzetta",
            description: "“Muth” Bianco Provincia di Pavia IGP",
            vol: "Muller Thurgau 100%",
            price: 26,
          },
          {
            id: 3,
            name: "Az. Agr Torrazzetta",
            description: "“Racà” Prov. Di Pavia Igp 2016",
            vol: "Chardonnay 100% (vol. 12,5%)",
            price: 25,
          },
          {
            id: 4,
            name: "Isimbarda",
            description:
              "“Vigna Martina” Riesling Sup. Oltrepò Pavese Doc 2021",
            vol: "Riesling 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 5,
            name: "Az. Agr. Vanzini",
            description: "Pinot Grigio Oltrepo P. Doc 2022",
            vol: "Pinot grigio 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 6,
            name: "Az. Agr. Vanzini",
            description: "“Assedio” Moscato Provincia di Pavia Igt 2021",
            vol: "Moscato 100% (VINIFICATO SECCO) (vol. 12%)",
            price: 24,
          },
        ],
      },
      {
        id: "bianchi-mossi",
        title: "Vini bianchi mossi",
        items: [
          {
            id: 0,
            name: "Picchioni",
            description: "“Soleluna” vino bianco frizzante 2021",
            vol: "Pinot nero 100% (vol. 12,5%)",
            price: 24,
          },
          {
            id: 1,
            name: "Az. Agr. Vanzini",
            description: "Riesling frizzante Oltrepò P. Doc 2022",
            vol: "Riesling Renano 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 2,
            name: "Az. Agr. Vanzini",
            description: "Malvasia vino bianco frizzante 2022",
            vol: "Malvasia 100% (vinificato secco) (vol. 11%)",
            price: 23,
          },
        ],
      },
      {
        id: "rosati",
        title: "Vini rosati",
        items: [
          {
            id: 0,
            name: "Travaglino",
            description: "“Ramato” Pinot Grigio Oltrepò P. Doc 2022",
            vol: "Pinot Grigio 100% (vol. 12,5%)",
            price: 26,
          },
          {
            id: 1,
            name: "Az. Agr. Torrazzetta",
            description: "“Grimarò” Pinot grigio Igt 2020",
            vol: "Pinot Nero 90%, Pinot Grigio 10% (vol. 12,5%)",
            price: 23,
          },
          {
            id: 2,
            name: "Az. Agr. Vanzini",
            description:
              "“Pianeta Rosa” Pinot nero frizzante Oltrepò P. Doc 2021",
            vol: "Pinot nero 100% (vol. 12%)",
            price: 22,
          },
        ],
      },
      {
        id: "rossi-fermi",
        title: "Vini rossi fermi",
        items: [
          {
            id: 0,
            name: "Fiamberti",
            description: "Buttafuoco Storico “Vigna Solenga” O. P. Doc 2017",
            vol: "Croatina 60%, Barbera 30%, ughetta di canneto 5%, uva rara 5% (vol.15,5%)",
            price: 65,
          },
          {
            id: 1,
            name: "Fiamberti",
            description:
              "Buttafuoco Storico “Vigna Sacca del Prete” O. P. Doc 2018",
            vol: "Croatina 60%,Barbera 30%,ughetta di canneto 5%,uva rara 5%(vol.15,5%)",
            price: 48,
          },
          {
            id: 2,
            name: "Picchioni",
            description: "“Solinghino” Buttafuoco Oltrepò P. Doc 2021",
            vol: "Croatina, barbera, vespolina (% variabili secondo annata) (vol. 14%)",
            price: 25,
          },
          {
            id: 3,
            name: "Fiamberti",
            description: "“Il Cacciatore” Buttafuoco Doc 2021",
            vol: "Croatina 60%,Barbera 30%,ughetta di canneto 5%, uva rara 5% (vol. 14%)",
            price: 25,
          },
          {
            id: 4,
            name: "Isimbarda",
            description: "“Costa di Annibale” Croatina Prov. Di Pavia Igt 2019",
            vol: "Croatina 100% (vol. 14,5%)",
            price: 25,
          },
          {
            id: 5,
            name: "Le Dinastie",
            description: "“Antico” Croatina Prov. Di Pavia Igt 2020",
            vol: "Croatina 90%, Pinot Nero 10% (vol. 15%)",
            price: 25,
          },
          {
            id: 6,
            name: "Marchesi di Montalto",
            description: "“Pizzotorto” Pinot Nero Riserva Oltrepo P. Doc 2015",
            vol: "Pinot nero 100% (vol. 12,5%)",
            price: 44,
          },
          {
            id: 7,
            name: "Le Dinastie",
            description: "“Compay” Pinot Nero Riserva Oltrepò P. Doc 2018",
            vol: "Pinot Nero 100% (vol. 15%)",
            price: 38,
          },
          {
            id: 8,
            name: "Marchesi di Montalto",
            description: "“Pero’ ” Prov. Di Pavia Igt 2020",
            vol: "Pinot nero 100% (vol. 13%)",
            price: 33,
          },
          {
            id: 9,
            name: "Mon Carul",
            description: "“Fioravanti” Pinot nero Oltrepo P. Doc 2022",
            vol: "Pinot nero 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 10,
            name: "Az. Agr. Torrazzetta",
            description: "“Tre Querce” Pinot nero Prov. Di Pavia Igp 2020",
            vol: "Pinot nero 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 11,
            name: "Travaglino",
            description: "“Campo dei Ciliegi” Barbera Oltrepo P. Doc 2019",
            vol: "Barbera 100% (vol. 13,5%)",
            price: 23,
          },
          {
            id: 12,
            name: "Fiamberti",
            description: "“Monte Acutello” Rosso riserva O. Pavese DOC 2007",
            vol: "Croatina 50% , Barbera 50 % (vol. 14,5%)",
            price: 34,
          },
          {
            id: 13,
            name: "Mon Carul",
            description: "“Perorossino” Vino rosso Igt 2017",
            vol: "Croatina, Barbera, uva rara, nibi e moradella (% variabili secondo annata) (vol.14,5%)",
            price: 25,
          },
        ],
      },
      {
        id: "rossi-mossi",
        title: "Vini rossi mossi",
        items: [
          {
            id: 0,
            name: "Picchioni",
            description:
              "“Da Cima a Fondo” Vino Rosso Non filtrato Met. Ancestrale 2020",
            vol: "Croatina 70%, Uva Rara 30% (vol. 13%)",
            price: 29,
          },
          {
            id: 1,
            name: "Az. Agr. Torrazzetta",
            description: "“Pavarolo” Met. Classico Vsq Brut s.a.",
            vol: "Croatina 40%, Barbera 30%, Pinot Nero 30% (vol. 13,5%)",
            price: 25,
          },
          {
            id: 2,
            name: "Isimbarda",
            description: "Barbera Oltrepo Pavese Doc 2019",
            vol: "Barbera 100% (vol. 14%)",
            price: 24,
          },
          {
            id: 3,
            name: "Mon Carul",
            description: "“Vigio” Bonarda Oltrepo P. Doc 2021",
            vol: "Croatina 100% (vol. 13,5%)",
            price: 22,
          },
        ],
      },
    ],
  },
  {
    id: "loc-ita",
    località: "Italia",
    categorie: [
      {
        id: "bol",
        title: "Bollicine",
        items: [
          {
            id: 0,
            region: "Valle D'Aosta",
            name: "Cave Mont Blanc",
            description:
              "Blanc de Morgex et de la Salle Vallee d’Aoste Doc Brut 2019",
            vol: "Prie Blanc 100% (vol. 12%)",
            price: 30,
          },
          {
            id: 1,
            region: "Piemonte",
            name: "Massimo Rivetti",
            description: "Alta Langa Docg Met. Classico Brut 2019",
            vol: "Pinot nero 85%, Chardonnay 15% (vol. 12,5%)",
            price: 36,
          },
          {
            id: 2,
            region: "Lombardia",
            name: "Derbusco Cives",
            description: "“Crisalis” Franciacorta Docg Blanc de Noir Brut 2017",
            vol: "Pinot nero 100% (vol. 12%)",
            price: 63,
          },
          {
            id: 3,
            region: "Lombardia",
            name: "La Valle",
            description: "Franciacorta Rosè Docg Brut 2017",
            vol: "Pinot nero 100% (vol. 12,5%)",
            price: 55,
          },
          {
            id: 4,
            region: "Lombardia",
            name: "La Valle",
            description: "“Regium” Franciacorta Docg Brut 2013",
            vol: "Chardonnay 100% (vol. 12,5%)",
            price: 52,
          },
          {
            id: 5,
            region: "Lombardia",
            name: "ZeroSpaccato",
            description: "Franciacorta Saten Docg Brut s.a.",
            vol: "Chardonnay 100% (vol. 12,5%)",
            price: 45,
          },
          {
            id: 6,
            region: "Lombardia",
            name: "ZeroSpaccato",
            description: "Franciacorta Docg Brut Nature s.a.",
            vol: "Chardonnay 100% (vol. 12,5%)",
            price: 40,
          },
          {
            id: 7,
            region: "Trentino - Alto Adige",
            name: "Endrizzi",
            description: "Trento Doc Brut 2019",
            vol: "Chardonnay 60%, Pinot Nero 40% (vol. 12,5%)",
            price: 35,
          },
          {
            id: 8,
            region: "Veneto",
            name: "L’Antica Quercia",
            description:
              "“Ario” Prosecco C. Vald. Rive di Scomingo Docg Extra Dry 2021",
            vol: "Glera 100% (vol. 11,5%)",
            price: 26,
          },
          {
            id: 9,
            region: "Emilia Romagna",
            name: "Cavaliera",
            description: "“Elena” Pignoletto di Modena Dop Vino frizzante 2020",
            vol: "Pignoletto 100% (vol. 11%)",
            price: 28,
          },
        ],
      },
      {
        id: "bianchi",
        title: "Vini bianchi",
        items: [
          {
            id: 0,
            region: "Valle d’Aosta",
            name: "La Vrille",
            description: "Chambave Muscat Vallee d’Aoste Dop 2020",
            vol: "Muscat petit grain 100% (vol. 14%)",
            price: 33,
          },
          {
            id: 1,
            region: "Valle d’Aosta",
            name: "Elio Ottin",
            description: "Petite Arvine Vallee d’Aoste Dop 2021",
            vol: "Petite Arvine 100% (vol. 14,5%)",
            price: 33,
          },
          {
            id: 2,
            region: "Piemonte",
            name: "Canevaro Luca",
            description:
              "“Cà degli Olmi” Derthona Colli Tortonesi Timorasso Doc 2",
            vol: "Timorasso 100% (vol. 14%)",
            price: 33,
          },
          {
            id: 3,
            region: "Piemonte",
            name: "Marco Porello",
            description: "“Camestri” Roero Arneis Docg 2021",
            vol: "Arneis 100% (vol. 13,5%)",
            price: 26,
          },
          {
            id: 4,
            region: "Veneto",
            name: "Le Battistelle",
            description: "“Battistelle” Soave Classico Doc 2021",
            vol: "Garganega 100% (vol. 12,5%)",
            price: 25,
          },
          {
            id: 5,
            region: "Veneto",
            name: "L’Antica Quercia",
            description: "“Su Alto” Indigeno col fondo Vino Frizzante 2020",
            vol: "Glera 100% (vol. 11%)",
            price: 24,
          },
          {
            id: 6,
            region: "Trentino - Alto Adige",
            name: "Endrizzi",
            description: "Gewurztraminer Trentino Doc 2021",
            vol: "Gewurztraminer 100% (vol. 13,5%)",
            price: 28,
          },
          {
            id: 7,
            region: "Trentino - Alto Adige",
            name: "Valle Isarco",
            description: "“Aristos” Sylvaner Alto Adige Valle Isarco Doc 2021",
            vol: "Sylvaner 100% (vol. 14%)",
            price: 27,
          },
          {
            id: 8,
            region: "Trentino - Alto Adige",
            name: "Vindimian Rudi",
            description: "“780 slm” Kerner Vigneti delle Dolomiti Igt 2019",
            vol: "Kerner 100% (vol. 12%)",
            price: 27,
          },
          {
            id: 9,
            region: "Trentino - Alto Adige",
            name: "Valle Isarco",
            description: "Muller Thurgau Alto Adige Valle Isarco Doc 2021",
            vol: "Muller thurgau 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 10,
            region: "Friuli Venezia Giulia",
            name: "Kocjancic Rado",
            description: "Vitovska Carso Doc 2021",
            vol: "Vitovska 100% (vol. 12,5%)",
            price: 27,
          },
          {
            id: 11,
            region: "Friuli Venezia Giulia",
            name: "Grillo Jole",
            description: "Sauvignon Colli Orientali Doc 2021",
            vol: "Sauvignon 100% (vol. 13,5%)",
            price: 26,
          },
          {
            id: 12,
            region: "Friuli Venezia Giulia",
            name: "Masut da Rive",
            description: "Chardonnay Isonzo del Friuli Doc 2021",
            vol: "Chardonnay 100% (vol. 12,5%)",
            price: 26,
          },
          {
            id: 13,
            region: "Friuli Venezia Giulia",
            name: "Komjanc",
            description: "Ribolla Gialla Colli Orientali Doc 2021",
            vol: "Ribolla gialla 100% (vol. 12,5%)",
            price: 25,
          },
          {
            id: 14,
            region: "Liguria",
            name: "Sancio",
            description: "Pigato Riviera Ligure di Ponente Doc 2021",
            vol: "Pigato 100% (vol. 13%)",
            price: 26,
          },
          {
            id: 15,
            region: "Liguria",
            name: "La Baracca",
            description: "“Mistic’o” Vino Bianco 2022",
            vol: "Vermentino, Albarola, Bosco (% variabili secondo annata) (vol. 12,5%)",
            price: 23,
          },
          {
            id: 16,
            region: "Toscana",
            name: "CappellaSantAndrea",
            description: "Vernaccia di San Gimignano Docg 2021",
            vol: "Vernaccia 100% (vol. 13%)",
            price: 25,
          },
          {
            id: 17,
            region: "Umbria",
            name: "Bennicelli",
            description: "Vermentino Umbria Igt 2022",
            vol: "Vermentino 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 18,
            region: "Marche",
            name: "Fattoria Nanni",
            description:
              "“Origini” Verdicchio Castelli di Jesi Cl. Sup. Doc 2020",
            vol: "Verdicchio 100% (vol. 13%)",
            price: 27,
          },
          {
            id: 19,
            region: "Marche",
            name: "Carminucci",
            description: "“Casta” Passerina Marche Igt 2021",
            vol: "Passerina 100% (vol. 12%)",
            price: 24,
          },
          {
            id: 20,
            region: "Campania",
            name: "Fattoria La Rivolta",
            description: "Greco Taburno Sannio Dop 2022",
            vol: "Greco 100% (vol. 12%)",
            price: 24,
          },
          {
            id: 21,
            region: "Campania",
            name: "La Sibilla",
            description: "“Campi Flegrei” Falanghina Doc 2021",
            vol: "Falanghina 100% (vol. 12%)",
            price: 25,
          },
          {
            id: 22,
            region: "Calabria",
            name: "Cantine Spadafora",
            description: "“Lunapiena” Donnici Terre di Cosenza Dop 2021",
            vol: "Greco bianco, malvasia, mantonico (% variabili secondo annata) (vol. 13%)",
            price: 23,
          },
          {
            id: 23,
            region: "Calabria",
            name: "Cantine Spadafora",
            description: "“Dolcemare” Donnici Terre di Cosenza Dop 2021",
            vol: "Greco bianco, malvasia (% variabili secondo annata) (vol. 13%)",
            price: 23,
          },
          {
            id: 24,
            region: "Sicilia",
            name: "Tenuta Gatto",
            description: "“Ardalia” Bianco Terre Siciliane Igt 2020",
            vol: "Nerello Mascalese 100% (vol. 12%)",
            price: 29,
          },
          {
            id: 25,
            region: "Sicilia",
            name: "Horus",
            description: "“Sole e Terra” Bianco Sicilia Doc 2021",
            vol: "Grillo 50%, Insolia 50% (vol. 12%)",
            price: 26,
          },
          {
            id: 26,
            region: "Sicilia",
            name: "Baroni di Pianogrillo",
            description: "Grecanico Terre Siciliane Igt 2021",
            vol: "Grecanico 100% (vol. 12,5%)",
            price: 25,
          },
          {
            id: 27,
            region: "Sardegna",
            name: "Tanca Raina",
            description: "Vermentino di Gallura Superiore Docg 2020",
            vol: "Vermentino 100% (vol. 14%)",
            price: 28,
          },
        ],
      },
      {
        id: "rosati",
        title: "Vini rosati",
        items: [
          {
            id: 0,
            region: "Veneto",
            name: "Tantini",
            description: "“Il Rosè” Chiaretto di Bardolino Doc 2021",
            vol: "Corvina, Rondinella, Molinara (% variabili secondo annata) (vol. 12,5%)",
            price: 25,
          },
          {
            id: 1,
            region: "Campania",
            name: "Fattoria La Rivolta",
            description:
              "“Le Mongolfiere a San Bruno” Aglianico del Taburno Docg 2021",
            vol: "Aglianico 100% (vol. 13,5%)",
            price: 25,
          },
          {
            id: 2,
            region: "Umbria",
            name: "Due Vigne",
            description: "“Torre Penna” Rosato Umbria Igt 2021",
            vol: "Sangiovese 100% (vol. 12,5%)",
            price: 24,
          },
          {
            id: 3,
            region: "Emilia Romagna",
            name: "Paltrinieri",
            description: "“Leclisse” Lambrusco di Sorbara Rosato Doc 2022",
            vol: "Lambrusco di Sorbara 100% (vol. 11%)",
            price: 24,
          },
          {
            id: 4,
            region: "Trentino - Alto Adige",
            name: "Endrizzi",
            description: "“Dalis Rosè” Vigneti delle Dolomiti Igp 2022",
            vol: "Teroldego 60%, Sauvignon Blanc 40% (vol. 12%)",
            price: 22,
          },
        ],
      },
      {
        id: "rossi",
        title: "Vini rossi",
        items: [
          {
            id: 0,
            region: "Valle D'Aosta",
            name: "La Vrille",
            description: "Vuillermin Vallee d’ Aoste Doc 2019",
            vol: "Nebbiolo 100% (vol. 14%)",
            price: 33,
          },
          {
            id: 1,
            region: "Valle D'Aosta",
            name: "Chateau Fuillet",
            description: "Torrette Vallee d’ Aoste Doc 2022",
            vol: "Petit Rouge 90%, Mayolet 10% (vol. 14%)",
            price: 27,
          },
          {
            id: 2,
            region: "Piemonte",
            name: "Parusso",
            description: "“Bussia” Barolo Docg 2018",
            vol: "Nebbiolo 100% (vol. 15%)",
            price: 135,
          },
          {
            id: 3,
            region: "Piemonte",
            name: "Parusso",
            description: "“Mosconi” Barolo Docg 2018",
            vol: "Nebbiolo 100% (vol. 15%)",
            price: 126,
          },
          {
            id: 4,
            region: "Piemonte",
            name: "Parusso",
            description: "“Perarmando” Barolo Docg 2019",
            vol: "Nebbiolo 100% (vol. 14,5%)",
            price: 85,
          },
          {
            id: 5,
            region: "Piemonte",
            name: "Socrè",
            description: "Barbaresco Docg 2019",
            vol: "Nebbiolo 100% (vol. 14,5%)",
            price: 57,
          },
          {
            id: 6,
            region: "Piemonte",
            name: "Virna Borgogno",
            description: "“IL” Nebbiolo Langhe Doc 2021",
            vol: "Nebbiolo 100% (vol. 14%)",
            price: 29,
          },
          {
            id: 7,
            region: "Piemonte",
            name: "Mauro Veglio",
            description: "Barbera d’Alba Doc 2021",
            vol: "Barbera 100% (vol. 14,5%)",
            price: 28,
          },
          {
            id: 8,
            region: "Piemonte",
            name: "Socrè",
            description: "Barbera d’Asti Docg 2020",
            vol: "Barbera 100% (vol. 14,5%)",
            price: 28,
          },
          {
            id: 9,
            region: "Piemonte",
            name: "Canevaro Luca",
            description: "Monleale Colli Tortonesi DOC 2017",
            vol: "Barbera 100% (vol. 15%)",
            price: 33,
          },
          {
            id: 10,
            region: "Piemonte",
            name: "Luigi Tacchino",
            description: "Dolcetto di Ovada DOC 2017",
            vol: "Dolcetto 100% (vol. 13,5%)",
            price: 26,
          },
          {
            id: 11,
            region: "Piemonte",
            name: "Az. Agr. Gatto",
            description: "“Caresana” Ruchè di Castagnole Monferrato Docg 2022",
            vol: "Ruchè 100% (vol. 15,5%)",
            price: 25,
          },
          {
            id: 12,
            region: "Piemonte",
            name: "Cascina Gilli",
            description: "“Il Forno” Freisa d’Asti Doc 2019",
            vol: "Freisa 100% (vol. 13%)",
            price: 23,
          },
          {
            id: 13,
            region: "Lombardia",
            name: "Scersce",
            description: "“Flammante” Inferno Valtellina Sup Docg 2019",
            vol: "Chiavennasca 100% (nebbiolo) (vol. 15%)",
            price: 39,
          },
          {
            id: 14,
            region: "Lombardia",
            name: "Caven",
            description: "“Messere” Sforzato di Valtellina Docg 2017",
            vol: "Chiavennasca 100% (nebbiolo). (vol. 16%)",
            price: 68,
          },
          {
            id: 15,
            region: "Trentino - Alto Adige",
            name: "Endrizzi",
            description: "Lagrein Trentino Dop 2021",
            vol: "Lagrein 100% (vol. 12,5%)",
            price: 27,
          },
          {
            id: 16,
            region: "Friuli Venzia Giulia",
            name: "Tarlao",
            description: "Refosco Venezia Giulia Igt 2021",
            vol: "Refosco dal peduncolo rosso 100% (vol. 13%)",
            price: 24,
          },
          {
            id: 17,
            region: "Friuli Venzia Giulia",
            name: "Ronco delle Betulle",
            description: "“Rosso” Venezia Giulia Igt 2022",
            vol: "Merlot 50%, Cabernet Franc 50% (vol. 13,5%)",
            price: 22,
          },
          {
            id: 18,
            region: "Veneto",
            name: "Brigaldara",
            description: "Amarone della Valpolicella Classico Docg 2017",
            vol: "Corvina 47%, Corvinone 39%, Rondinella 6%, altre 8% (vol. 16,5%)",
            price: 96,
          },
          {
            id: 19,
            region: "Veneto",
            name: "Brigaldara",
            description: "Amarone della Valpolicella “Cavolo” Docg 2017",
            vol: "Corvina 47%, Corvinone 39%, Rondinella 6%, altre 8% (vol. 16%)",
            price: 56,
          },
          {
            id: 20,
            region: "Veneto",
            name: "Fumanelli",
            description: "Valpolicella Ripasso Classico Sup. Doc 2020",
            vol: "Corvinone 50%, Corvina 30%, Rondinella 20% (vol. 13%)",
            price: 30,
          },
          {
            id: 21,
            region: "Veneto",
            name: "Villa Spinosa",
            description: "“Figari” Valpolicella Cl. Sup. Doc 2020",
            vol: "Corvina 40%, Corvinone 40%, rondinella 20% (vol. 13,5%)",
            price: 26,
          },
          {
            id: 22,
            region: "Emilia Romagna",
            name: "Cavaliera",
            description:
              "“Federico”Lambrusco Gasparossa di Castelvetro Dop 2021",
            vol: "Lambrusco Gasparossa 100% (vol. 11,5%) (FRIZZANTE)",
            price: 24,
          },
          {
            id: 23,
            region: "Toscana",
            name: "Tenuta Sette Ponti",
            description: "“Orma” Toscana Igt 2019",
            vol: "Merlot 50% cabernet sauvignon 30% cabernet franc 20% (vol. 15%)",
            price: 118,
          },
          {
            id: 24,
            region: "Toscana",
            name: "Tenuta di Collosorbo",
            description: "Brunello di Montalcino Docg 2018",
            vol: "Sangiovese 100% (vol. 14,5%)",
            price: 65,
          },
          {
            id: 25,
            region: "Toscana",
            name: "Podere dei Musi Bolgheri Doc 2020",
            description: "Merlot, Petit Verdot, Cabernet Sauvignon",
            vol: "Syrah (%variabili secondo annata) (vol.13,5)",
            price: 33,
          },
          {
            id: 26,
            region: "Toscana",
            name: "Quercia al Poggio",
            description: "Chianti Classico Docg 2021",
            vol: "Sangiovese 100% (vol. 13,5%)",
            price: 30,
          },
          {
            id: 27,
            region: "Toscana",
            name: "La Fornace",
            description: "Rosso di Montalcino Doc 2021",
            vol: "Sangiovese 100% (vol. 14%)",
            price: 27,
          },
          {
            id: 28,
            region: "Toscana",
            name: "I Cavallini",
            description: "Morellino di Scansano DOCG 2021",
            vol: "Sangiovese 85%, Ciliegiolo e Alicante 15%. (vol. 14,5%)",
            price: 25,
          },
          {
            id: 29,
            region: "Abruzzo",
            name: "Ausonia",
            description:
              "“Apollo” Montepulciano d’Abruzzo Colline Teramane Docg 2019",
            vol: "Montepulciano d’abruzzo 100% (vol. 13,5%)",
            price: 28,
          },
          {
            id: 30,
            region: "Basilicata",
            name: "Quarta Generazione",
            description: "“A Cerasole” Aglianico del Vulture Dop 2019",
            vol: "Aglianico del Vulture 100% (vol. 14%)",
            price: 25,
          },
          {
            id: 31,
            region: "Puglia",
            name: "Az. Agr. Mocavero",
            description: "“Sire” Primitivo del Salento Igp 2021",
            vol: "Primitivo 100% (vol. 12,5%)",
            price: 25,
          },
          {
            id: 32,
            region: "Puglia",
            name: "Feudi Salentini",
            description: "“125” Negramaro del Salento Igp 2020",
            vol: "Negramaro 100% (vol. 12,5%)",
            price: 24,
          },
          {
            id: 33,
            region: "Calabria",
            name: "Spadafora",
            description: "“Telesio” Terre di Cosenza Donnici Dop 2017",
            vol: "Magliocco dolce, greco nero 100%, Malvasia nera (% variabili secondo annata) (vol. 13,5)",
            price: 27,
          },
          {
            id: 34,
            region: "Calabria",
            name: "Spadafora",
            description: "“Nerello” Calabria rosso IGP 2019",
            vol: "Neretto calabrese 100%. (vol. 13,5%)",
            price: 25,
          },
          {
            id: 35,
            region: "Calabria",
            name: "Spadafora",
            description: "“Solenero” Calabria rosso IGP 2021",
            vol: "Magliocco dolce 50%, Merlot 50%. (vol. 13%)",
            price: 23,
          },
          {
            id: 35,
            region: "Sicilia",
            name: "Baroni di Pianogrillo",
            description: "“Frappato” Terre Siciliane Igt 2021",
            vol: "Frappato 100% (vol. 12,5%)",
            price: 26,
          },
        ],
      },
    ],
  },
];
